# -*- coding: utf-8 -*-
"""fandom_dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KjM3ok-kaoEOp7H13hLza_gJ8NHR0I0a
"""

import streamlit as st
import pandas as pd


@st.cache_data

def load_data():
    df = pd.read_json("starwars_dataset.json")
    return df

df = load_data()

# Заголовок
st.title("Fandom Hypergraph: Star Wars Dashboard")

# Статистика
st.header("📊 Общая статистика")
st.markdown(f"**Количество статей:** {df['document_id'].nunique()}")
st.markdown(f"**Количество чанков:** {len(df)}")
st.markdown(f"**Средняя длина чанка (в словах):** {int(df['chunk_text'].apply(lambda x: len(str(x).split())).mean())}")
st.markdown(f"**Среднее количество ссылок на чанк:** {round(df['outgoing_links'].apply(len).mean(), 2)}")

# Фильтрация и сортировка
st.header("🔍 Поиск и фильтрация")

search_term = st.text_input("Поиск по заголовку статьи")
sort_option = st.selectbox("Сортировать по", ["Количество чанков", "Количество ссылок"])

filtered = df.copy()
if search_term:
    filtered = filtered[filtered['title'].str.contains(search_term, case=False, na=False)]

if sort_option == "Количество чанков":
    sort_df = filtered.groupby("title")["chunk_id"].count().reset_index(name="chunks").sort_values(by="chunks", ascending=False)
elif sort_option == "Количество ссылок":
    sort_df = filtered.groupby("title")["outgoing_links"].apply(lambda x: sum(len(l) for l in x)).reset_index(name="links").sort_values(by="links", ascending=False)

st.dataframe(sort_df.head(20))

# Просмотр статьи и чанков
st.header("📚 Просмотр статьи")
unique_titles = sorted(filtered['title'].unique())
selected_title = st.selectbox("Выберите статью", unique_titles)

chunks = filtered[filtered['title'] == selected_title].sort_values(by="chunk_id")
for _, row in chunks.iterrows():
    st.subheader(f"Чанк {row['chunk_id']}")
    st.text_area("Текст чанка", value=row['chunk_text'], height=150)
    st.markdown(f"**Ссылается на:** {', '.join(row['outgoing_links']) if row['outgoing_links'] else '—'}")
    st.markdown(f"[Открыть статью на Fandom]({row['source']})")